services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
    command: >
      sh -c  "python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python manage.py collectstatic --no-input &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8000 --log-level info"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app





